// generated by cppGen.go - do not edit
#ifndef CPPLEXERTEMPLATE_AUTOMATA_H
#define CPPLEXERTEMPLATE_AUTOMATA_H


#include <memory>
#include "CharReader.h"

class Automata {
public:
    virtual void runGreedy(CharReader& reader) = 0;

    virtual std::string name() = 0;

    virtual ~Automata() = default;
};


class NUM : public Automata {
    void runGreedy(CharReader& reader) override;

    std::string name() override;
};
class IDENT : public Automata {
    void runGreedy(CharReader& reader) override;

    std::string name() override;
};
class COMMENT : public Automata {
    void runGreedy(CharReader& reader) override;

    std::string name() override;
};

#endif //CPPLEXERTEMPLATE_AUTOMATA_H