// generated by cppGen.go - do not edit
#ifndef CPPLEXERTEMPLATE_LEXER_H
#define CPPLEXERTEMPLATE_LEXER_H


#include <vector>
#include <memory>
#include <ostream>
#include "CharReader.h"
#include "Automata.h"

using TokenType = std::string;
using TokenValue = std::string;

class Token {
public:
    Token(TokenType type, TokenValue token);

    TokenType type;
    TokenValue token;

    friend std::ostream &operator<<(std::ostream &os, const Token &token);
};

class Lexer {
public:
    explicit Lexer(CharReader& charReader);

    Token nextToken();

    bool hasNext();

    void skipWhitespace();

private:
    CharReader &charReader;
    std::vector<std::unique_ptr<Automata>> automatas = std::vector<std::unique_ptr<Automata>>();
};


#endif //CPPLEXERTEMPLATE_LEXER_H